development:
  adapter: postgresql
  encoding: utf8
  database: TMS_AB_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: TMS_AB_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: TMS_AB_production
  pool: 5
  username: 
  password: